name: "构建和发布"

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: 安装 Rust
        uses: dtolnay/rust-toolchain@stable

      - name: 安装依赖 (Ubuntu)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: 安装前端依赖
        run: npm install

      - name: 构建前端
        run: npm run build

      - name: 构建 Tauri 应用
        uses: tauri-apps/tauri-action@v0.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "Link to Text Desktop ${{ github.ref_name }}"
          releaseBody: "查看 CHANGELOG.md 获取详细更新内容。"
          releaseDraft: true
          prerelease: false 